config/routes.rb
Rails.application.routes.draw do
  get 'doses/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show, :new, :create]  do
    resources :doses, only: [:new, :create]
  end
  delete "doses/:id", to: "doses#destroy", as: :dose # or resources :doses, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :ingredient, uniqueness: {scope: :cocktail}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail = dose.cocktail
    dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td>
          <ul class="list-unstyled">
            <% cocktail.doses.each do |dose| %>
            <li> <%= dose.description %> of <%= dose.ingredient.name %> </li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', cocktail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div>
      <%= f.button :submit, class: "form-actions btn btn-primary" %>
    </div>
  <% end %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <h2>Ingredients:</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Doses</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.description %> of <%= dose.ingredient.name %></td>

              <td class="text-right"><%= link_to 'Delete dose', dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'%></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <h3>Adding a new dose to <%= @cocktail.name %></h3>

      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :description, label: "Amount" %>
          <%= f.association :ingredient%>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= link_to 'Back', cocktails_path, class: "btn btn-default" %>
      </div>
    </div>

  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>